---

- name: Ensure nginx installed
  ansible.builtin.package:
    name: nginx

- name: Ensure nginx is enabled and startet
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Ensure disable /etc/nginx/sites-enabled/default
  ansible.builtin.file:
    name: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: Ensure /etc/nginx/sites-available/{{ nginx_server_FQDN }}_80.conf
  ansible.builtin.template:
    src: nginx_80.conf.j2
    dest: /etc/nginx/sites-available/{{ nginx_server_FQDN }}.conf
  notify: restart nginx

- name: Ensure /etc/nginx/sites-enabled/{{ nginx_server_FQDN }}_80.conf
  ansible.builtin.file:
    src: /etc/nginx/sites-available/{{ nginx_server_FQDN }}_80.conf
    dest: /etc/nginx/sites-enabled/{{ nginx_server_FQDN }}_80.conf
    state: link
  notify: restart nginx

- name: Ensure /etc/nginx/sites-available/{{ nginx_server_FQDN }}_443.conf
  ansible.builtin.template:
    src: nginx_port.conf.j2
    dest: /etc/nginx/sites-available/{{ nginx_server_FQDN }}_443.conf
  loop:
    - { port: 443, location: '{{ nginx_location_stanzas }}' }
  notify: restart nginx

- name: Ensure /etc/nginx/sites-enabled/{{ nginx_server_FQDN }}_443.conf
  ansible.builtin.file:
    src: /etc/nginx/sites-available/{{ nginx_server_FQDN }}_443.conf
    dest: /etc/nginx/sites-enabled/{{ nginx_server_FQDN }}_443.conf
    state: link
  notify: restart nginx

- name: Ensure /etc/nginx/sites-available/{{ nginx_server_FQDN }}_{{ item.port }}.conf
  ansible.builtin.template:
    src: nginx_port.conf.j2
    dest: /etc/nginx/sites-available/{{ nginx_server_FQDN }}_{{ item.port }}.conf
  loop: "{{ nginx_ssl_confs }}"
  notify: restart nginx

- name: Ensure /etc/nginx/sites-enabled/{{ nginx_server_FQDN }}_{{ item.port }}.conf
  ansible.builtin.file:
    src: /etc/nginx/sites-available/{{ nginx_server_FQDN }}_{{ item.port }}.conf
    dest: /etc/nginx/sites-enabled/{{ nginx_server_FQDN }}_{{ item.port }}.conf
    state: link
  loop: "{{ nginx_ssl_confs }}"
  notify: restart nginx

...