---

- name: Ensure nginx installed
  ansible.builtin.package:
    name: nginx
  when: nginx_install

- name: Ensure nginx is enabled and startet
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
  when: nginx_install

- name: Ensure disable "{{ nginx_configuration_home }}"/sites-enabled/default
  ansible.builtin.file:
    name: "{{ nginx_configuration_home }}/sites-enabled/default"
    state: absent
  notify: restart nginx

- name: Ensure "{{ nginx_configuration_home }}/sites-available/{{ nginx_server_FQDN }}_80.conf"
  ansible.builtin.template:
    src: nginx_80.conf.j2
    dest: "{{ nginx_configuration_home }}/sites-available/{{ nginx_server_FQDN }}_80.conf"
  notify: restart nginx

- name: Ensure "{{ nginx_configuration_home }}/sites-enabled/{{ nginx_server_FQDN }}_80.conf"
  ansible.builtin.file:
    src: "{{ nginx_configuration_home }}/sites-available/{{ nginx_server_FQDN }}_80.conf"
    dest: "{{ nginx_configuration_home }}/sites-enabled/{{ nginx_server_FQDN }}_80.conf"
    state: link
  notify: restart nginx

- name: Ensure "{{ nginx_configuration_home }}/sites-available/{{ nginx_server_FQDN }}_443.conf"
  ansible.builtin.template:
    src: nginx_port.conf.j2
    dest: "{{ nginx_configuration_home }}/sites-available/{{ nginx_server_FQDN }}_443.conf"
  loop:
    - { 
        port: 443, 
        location: nginx_location_stanzas, 
        proxy_port: "{{ nginx_443_proxy_port }}", 
        server_name: "{{ nginx_server_FQDN }}" 
      }
  notify: restart nginx

- name: Ensure "{{ nginx_configuration_home }}/sites-enabled/{{ nginx_server_FQDN }}_443.conf"
  ansible.builtin.file:
    src: "{{ nginx_configuration_home }}/sites-available/{{ nginx_server_FQDN }}_443.conf"
    dest: "{{ nginx_configuration_home }}/sites-enabled/{{ nginx_server_FQDN }}_443.conf"
    state: link
  notify: restart nginx

- name: Ensure "{{ nginx_configuration_home }}/sites-available/{{ nginx_server_FQDN }}_{{ item.port }}.conf"
  ansible.builtin.template:
    src: nginx_port.conf.j2
    dest: "{{ nginx_configuration_home }}/sites-available/{{ nginx_server_FQDN }}_{{ item.port }}.conf"
  loop: "{{ nginx_confs }}"
  notify: restart nginx

- name: Ensure "{{ nginx_configuration_home }}/sites-enabled/{{ nginx_server_FQDN }}_{{ item.port }}.conf"
  ansible.builtin.file:
    src: "{{ nginx_configuration_home }}/sites-available/{{ nginx_server_FQDN }}_{{ item.port }}.conf"
    dest: "{{ nginx_configuration_home }}/sites-enabled/{{ nginx_server_FQDN }}_{{ item.port }}.conf"
    state: link
  loop: "{{ nginx_confs }}"
  notify: restart nginx

...