---

- name: Ensure install nginx
  ansible.builtin.include_tasks: "nginx_install.yml"
  when: nginx_install

- name: Ensure nginx config
  ansible.builtin.include_tasks: "nginx_configure.yml"
  when: nginx_config

...